blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/zugobite/wallet/tree/main/docs
    about: Check out our documentation before opening an issue
  - name: Questions & Discussions
    url: https://github.com/zugobite/wallet/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
